function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug":"doctype html\r\nhead\r\n  meta(charset='utf-8')\r\n  meta(name='viewport' content='width=device-width, initial-scale=1.0')\r\n  meta(http-equiv='X-UA-Compatible' content='ie=edge')\r\n  title The Eagle\r\n  link(rel='stylesheet' href='css\u002Fbootstrap.css')\r\n  link(rel='stylesheet' href='css\u002Fmain.css')\r\n  link(rel='stylesheet' href='https:\u002F\u002Fpro.fontawesome.com\u002Freleases\u002Fv5.10.0\u002Fcss\u002Fall.css' integrity='sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p' crossorigin='anonymous')\r\n  link(rel='stylesheet' href='css\u002Fmedia.css')\r\n  link(rel='stylesheet' href='css\u002Fhover.css')\r\n  link(rel='stylesheet' href='css\u002Fanimate.css')\r\nsection.option-box\r\n  .settings-box\r\n    .toggle-settings\r\n      i.fas.fa-cogs\r\n    .settings-container\r\n      .option-box\r\n        h4 Colors\r\n        ul.colors-list\r\n          li.active(data-color='#FF9800')\r\n          li(data-color='#E91E63')\r\n          li(data-color='#009688')\r\n          li(data-color='#03A9F4')\r\n          li(data-color='#4CAF50')\r\n      button.reset-options Reset Options\r\nnav.navbar.navbar-default.navbar-fixed-top\r\n  .container\r\n    \u002F\u002F- Brand and toggle get grouped for better mobile display\r\n    .navbar-header\r\n      button.navbar-toggle.collapsed(type='button' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false')\r\n        span.sr-only Toggle navigation\r\n        span.icon-bar\r\n        span.icon-bar\r\n        span.icon-bar\r\n      a.navbar-brand.hvr-float(href='#')\r\n        | The \r\n        span.brandeag.hvr-grow-rotate Eagle\r\n    \u002F\u002F- Collect the nav links, forms, and other content for toggling\r\n    #bs-example-navbar-collapse-1.collapse.navbar-collapse\r\n      ul.nav.navbar-nav.navbar-right\r\n        li.active\r\n          a(href='index.html')\r\n            | Home \r\n            span.sr-only (current)\r\n        li\r\n          a(href='about.html') About\r\n        li\r\n          a(href='faq.html') FAQ\r\n        li.dropdown\r\n          a.dropdown-toggle(href='#' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false')\r\n            | Category \r\n            span.caret\r\n          ul.dropdown-menu\r\n            li\r\n              a(href='#') Security\r\n            li\r\n              a(href='#') FrontEnd\r\n            li\r\n              a(href='#') Network\r\n            li.divider(role='separator')\r\n            li\r\n              a(href='#') Bussnis Development\r\n    \u002F\u002F- \u002F.navbar-collapse\r\n  \u002F\u002F- \u002F.container-fluid\r\nsection.holder\r\n  .container\r\n    ol.breadcrumb\r\n      li\r\n        a(href='index.html') Home\r\n      li.active Data\r\nsection.faq.text-center\r\n  .container\r\n    h1 The Eagle FAQ\r\n    #accordion.panel-group(role='tablist' aria-multiselectable='true')\r\n      .panel.panel-default\r\n        #headingOne.panel-heading(role='tab')\r\n          h4.panel-title\r\n            a(role='button' data-toggle='collapse' data-parent='#accordion' href='#collapseOne' aria-expanded='true' aria-controls='collapseOne')\r\n              | Collapsible\r\n        #collapseOne.panel-collapse.collapse.in(role='tabpanel' aria-labelledby='headingOne')\r\n          .panel-body\r\n            | Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird\r\n            | on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft\r\n            | beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven&apos;t heard of them accusamus labore sustainable VHS.\r\n      .panel.panel-default\r\n        #headingTwo.panel-heading(role='tab')\r\n          h4.panel-title\r\n            a.collapsed(role='button' data-toggle='collapse' data-parent='#accordion' href='#collapseTwo' aria-expanded='false' aria-controls='collapseTwo')\r\n              | Collapsible\r\n        #collapseTwo.panel-collapse.collapse(role='tabpanel' aria-labelledby='headingTwo')\r\n          .panel-body\r\n            | Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird\r\n            | on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft\r\n            | beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven&apos;t heard of them accusamus labore sustainable VHS.\r\n      .panel.panel-default\r\n        #headingThree.panel-heading(role='tab')\r\n          h4.panel-title\r\n            a.collapsed(role='button' data-toggle='collapse' data-parent='#accordion' href='#collapseThree' aria-expanded='false' aria-controls='collapseThree')\r\n              | Collapsible\r\n        #collapseThree.panel-collapse.collapse(role='tabpanel' aria-labelledby='headingThree')\r\n          .panel-body\r\n            | Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird\r\n            | on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft\r\n            | beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven&apos;t heard of them accusamus labore sustainable VHS.\r\nsection.depart.wow.animate__pulse\r\n  .container\r\n    .row\r\n      .list-unstyled\r\n        li.col-md-2.col-xs-2\r\n          img.img-responsive.center-block.hvr-grow(src='image\u002Flogo.jpeg' alt='Dep1')\r\n        li.col-md-2.col-xs-2\r\n          img.img-responsive.center-block.hvr-grow(src='image\u002Flogo.jpeg' alt='Dep2')\r\n        li.col-md-2.col-xs-2\r\n          img.img-responsive.center-block.hvr-grow(src='image\u002Flogo.jpeg' alt='Dep3')\r\n        li.col-md-2.col-xs-2\r\n          img.img-responsive.center-block.hvr-grow(src='image\u002Flogo.jpeg' alt='Dep4')\r\n        li.col-md-2.col-xs-2\r\n          img.img-responsive.center-block.hvr-grow(src='image\u002Flogo.jpeg' alt='Dep5')\r\n        li.col-md-2.col-xs-2\r\n          img.img-responsive.center-block.hvr-grow(src='image\u002Flogo.jpeg' alt='Dep6')\r\nsection.footer.text-center\r\n  .container\r\n    .row\r\n      .col-lg-4\r\n        i.fas.fa-video\r\n        a Video\r\n      .col-lg-4\r\n        i.far.fa-newspaper\r\n        a Artical\r\n      .col-lg-4\r\n        i.fas.fa-building\r\n        a Department\r\n  .copyrigth\r\n    | CopyRigth &copy; 2021 \r\n    span  Design By A7med Ragab\r\nsection.loading\r\n  .sk-chase\r\n    .sk-chase-dot\r\n    .sk-chase-dot\r\n    .sk-chase-dot\r\n    .sk-chase-dot\r\n    .sk-chase-dot\r\n    .sk-chase-dot\r\na.backtotop(href='#' style='display: inline;')\r\n  i.fa.fa-arrow-circle-up\r\nscript(src='js\u002Fjquery-1.11.1.min.js')\r\nscript(src='js\u002Fjquery.nicescroll.min.js')\r\nscript(src='js\u002Fbootstrap.js')\r\nscript(src='js\u002Fplugin.js')\r\nscript(src='js\u002Fwow.js')\r\nscript.\r\n  new WOW().init();\r\n"};
var pug_indent = [];
;pug_debug_line = 1;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003C!DOCTYPE html\u003E";
;pug_debug_line = 2;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Chead\u003E";
;pug_debug_line = 3;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cmeta charset=\"utf-8\"\u003E";
;pug_debug_line = 4;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cmeta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Ctitle\u003E";
;pug_debug_line = 6;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "The Eagle\u003C\u002Ftitle\u003E";
;pug_debug_line = 7;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Clink rel=\"stylesheet\" href=\"css\u002Fbootstrap.css\"\u003E";
;pug_debug_line = 8;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Clink rel=\"stylesheet\" href=\"css\u002Fmain.css\"\u003E";
;pug_debug_line = 9;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Clink rel=\"stylesheet\" href=\"https:\u002F\u002Fpro.fontawesome.com\u002Freleases\u002Fv5.10.0\u002Fcss\u002Fall.css\" integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\" crossorigin=\"anonymous\"\u003E";
;pug_debug_line = 10;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Clink rel=\"stylesheet\" href=\"css\u002Fmedia.css\"\u003E";
;pug_debug_line = 11;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Clink rel=\"stylesheet\" href=\"css\u002Fhover.css\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Clink rel=\"stylesheet\" href=\"css\u002Fanimate.css\"\u003E\n\u003C\u002Fhead\u003E";
;pug_debug_line = 13;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Csection class=\"option-box\"\u003E";
;pug_debug_line = 14;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cdiv class=\"settings-box\"\u003E";
;pug_debug_line = 15;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"toggle-settings\"\u003E";
;pug_debug_line = 16;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ci class=\"fas fa-cogs\"\u003E\u003C\u002Fi\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 17;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"settings-container\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cdiv class=\"option-box\"\u003E";
;pug_debug_line = 19;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Ch4\u003E";
;pug_debug_line = 19;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Colors\u003C\u002Fh4\u003E";
;pug_debug_line = 20;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cul class=\"colors-list\"\u003E";
;pug_debug_line = 21;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Cli class=\"active\" data-color=\"#FF9800\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 22;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Cli data-color=\"#E91E63\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 23;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Cli data-color=\"#009688\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 24;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Cli data-color=\"#03A9F4\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 25;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Cli data-color=\"#4CAF50\"\u003E\u003C\u002Fli\u003E\n        \u003C\u002Ful\u003E\n      \u003C\u002Fdiv\u003E";
;pug_debug_line = 26;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cbutton class=\"reset-options\"\u003E";
;pug_debug_line = 26;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Reset Options\u003C\u002Fbutton\u003E\n    \u003C\u002Fdiv\u003E\n  \u003C\u002Fdiv\u003E\n\u003C\u002Fsection\u003E";
;pug_debug_line = 27;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Cnav class=\"navbar navbar-default navbar-fixed-top\"\u003E";
;pug_debug_line = 28;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cdiv class=\"container\"\u003E";
;pug_debug_line = 30;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"navbar-header\"\u003E";
;pug_debug_line = 31;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cbutton class=\"navbar-toggle collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\"\u003E";
;pug_debug_line = 32;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cspan class=\"sr-only\"\u003E";
;pug_debug_line = 32;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Toggle navigation\u003C\u002Fspan\u003E";
;pug_debug_line = 33;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cspan class=\"icon-bar\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 34;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cspan class=\"icon-bar\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 35;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cspan class=\"icon-bar\"\u003E\u003C\u002Fspan\u003E\u003C\u002Fbutton\u003E";
;pug_debug_line = 36;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca class=\"navbar-brand hvr-float\" href=\"#\"\u003E";
;pug_debug_line = 37;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "The ";
;pug_debug_line = 38;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cspan class=\"brandeag hvr-grow-rotate\"\u003E";
;pug_debug_line = 38;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Eagle\u003C\u002Fspan\u003E\u003C\u002Fa\u003E\n    \u003C\u002Fdiv\u003E";
;pug_debug_line = 40;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\"\u003E";
;pug_debug_line = 41;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cul class=\"nav navbar-nav navbar-right\"\u003E";
;pug_debug_line = 42;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli class=\"active\"\u003E";
;pug_debug_line = 43;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca href=\"index.html\"\u003E";
;pug_debug_line = 44;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Home ";
;pug_debug_line = 45;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cspan class=\"sr-only\"\u003E";
;pug_debug_line = 45;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "(current)\u003C\u002Fspan\u003E\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 46;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli\u003E";
;pug_debug_line = 47;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca href=\"about.html\"\u003E";
;pug_debug_line = 47;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "About\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 48;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli\u003E";
;pug_debug_line = 49;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca href=\"faq.html\"\u003E";
;pug_debug_line = 49;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "FAQ\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 50;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli class=\"dropdown\"\u003E";
;pug_debug_line = 51;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\"\u003E";
;pug_debug_line = 52;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Category ";
;pug_debug_line = 53;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cspan class=\"caret\"\u003E\u003C\u002Fspan\u003E\u003C\u002Fa\u003E";
;pug_debug_line = 54;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Cul class=\"dropdown-menu\"\u003E";
;pug_debug_line = 55;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            \u003Cli\u003E";
;pug_debug_line = 56;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca href=\"#\"\u003E";
;pug_debug_line = 56;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Security\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 57;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            \u003Cli\u003E";
;pug_debug_line = 58;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca href=\"#\"\u003E";
;pug_debug_line = 58;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "FrontEnd\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 59;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            \u003Cli\u003E";
;pug_debug_line = 60;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca href=\"#\"\u003E";
;pug_debug_line = 60;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Network\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 61;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            \u003Cli class=\"divider\" role=\"separator\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 62;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            \u003Cli\u003E";
;pug_debug_line = 63;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca href=\"#\"\u003E";
;pug_debug_line = 63;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Bussnis Development\u003C\u002Fa\u003E\u003C\u002Fli\u003E\n          \u003C\u002Ful\u003E\n        \u003C\u002Fli\u003E\n      \u003C\u002Ful\u003E\n    \u003C\u002Fdiv\u003E\n  \u003C\u002Fdiv\u003E\n\u003C\u002Fnav\u003E";
;pug_debug_line = 66;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Csection class=\"holder\"\u003E";
;pug_debug_line = 67;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cdiv class=\"container\"\u003E";
;pug_debug_line = 68;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Col class=\"breadcrumb\"\u003E";
;pug_debug_line = 69;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cli\u003E";
;pug_debug_line = 70;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca href=\"index.html\"\u003E";
;pug_debug_line = 70;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Home\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 71;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cli class=\"active\"\u003E";
;pug_debug_line = 71;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Data\u003C\u002Fli\u003E\n    \u003C\u002Fol\u003E\n  \u003C\u002Fdiv\u003E\n\u003C\u002Fsection\u003E";
;pug_debug_line = 72;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Csection class=\"faq text-center\"\u003E";
;pug_debug_line = 73;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cdiv class=\"container\"\u003E";
;pug_debug_line = 74;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Ch1\u003E";
;pug_debug_line = 74;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "The Eagle FAQ\u003C\u002Fh1\u003E";
;pug_debug_line = 75;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"panel-group\" id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\"\u003E";
;pug_debug_line = 76;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cdiv class=\"panel panel-default\"\u003E";
;pug_debug_line = 77;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cdiv class=\"panel-heading\" id=\"headingOne\" role=\"tab\"\u003E";
;pug_debug_line = 78;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Ch4 class=\"panel-title\"\u003E";
;pug_debug_line = 79;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\"\u003E";
;pug_debug_line = 80;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Collapsible\u003C\u002Fa\u003E\u003C\u002Fh4\u003E\n        \u003C\u002Fdiv\u003E";
;pug_debug_line = 81;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cdiv class=\"panel-collapse collapse in\" id=\"collapseOne\" role=\"tabpanel\" aria-labelledby=\"headingOne\"\u003E";
;pug_debug_line = 82;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Cdiv class=\"panel-body\"\u003E\n            ";
;pug_debug_line = 83;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird";
;pug_debug_line = 84;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            ";
;pug_debug_line = 84;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft";
;pug_debug_line = 85;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            ";
;pug_debug_line = 85;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven&apos;t heard of them accusamus labore sustainable VHS.\n          \u003C\u002Fdiv\u003E\n        \u003C\u002Fdiv\u003E\n      \u003C\u002Fdiv\u003E";
;pug_debug_line = 86;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cdiv class=\"panel panel-default\"\u003E";
;pug_debug_line = 87;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cdiv class=\"panel-heading\" id=\"headingTwo\" role=\"tab\"\u003E";
;pug_debug_line = 88;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Ch4 class=\"panel-title\"\u003E";
;pug_debug_line = 89;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\"\u003E";
;pug_debug_line = 90;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Collapsible\u003C\u002Fa\u003E\u003C\u002Fh4\u003E\n        \u003C\u002Fdiv\u003E";
;pug_debug_line = 91;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cdiv class=\"panel-collapse collapse\" id=\"collapseTwo\" role=\"tabpanel\" aria-labelledby=\"headingTwo\"\u003E";
;pug_debug_line = 92;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Cdiv class=\"panel-body\"\u003E\n            ";
;pug_debug_line = 93;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird";
;pug_debug_line = 94;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            ";
;pug_debug_line = 94;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft";
;pug_debug_line = 95;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            ";
;pug_debug_line = 95;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven&apos;t heard of them accusamus labore sustainable VHS.\n          \u003C\u002Fdiv\u003E\n        \u003C\u002Fdiv\u003E\n      \u003C\u002Fdiv\u003E";
;pug_debug_line = 96;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cdiv class=\"panel panel-default\"\u003E";
;pug_debug_line = 97;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cdiv class=\"panel-heading\" id=\"headingThree\" role=\"tab\"\u003E";
;pug_debug_line = 98;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Ch4 class=\"panel-title\"\u003E";
;pug_debug_line = 99;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\"\u003E";
;pug_debug_line = 100;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Collapsible\u003C\u002Fa\u003E\u003C\u002Fh4\u003E\n        \u003C\u002Fdiv\u003E";
;pug_debug_line = 101;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cdiv class=\"panel-collapse collapse\" id=\"collapseThree\" role=\"tabpanel\" aria-labelledby=\"headingThree\"\u003E";
;pug_debug_line = 102;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n          \u003Cdiv class=\"panel-body\"\u003E\n            ";
;pug_debug_line = 103;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird";
;pug_debug_line = 104;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            ";
;pug_debug_line = 104;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft";
;pug_debug_line = 105;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n            ";
;pug_debug_line = 105;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven&apos;t heard of them accusamus labore sustainable VHS.\n          \u003C\u002Fdiv\u003E\n        \u003C\u002Fdiv\u003E\n      \u003C\u002Fdiv\u003E\n    \u003C\u002Fdiv\u003E\n  \u003C\u002Fdiv\u003E\n\u003C\u002Fsection\u003E";
;pug_debug_line = 106;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Csection class=\"depart wow animate__pulse\"\u003E";
;pug_debug_line = 107;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cdiv class=\"container\"\u003E";
;pug_debug_line = 108;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"row\"\u003E";
;pug_debug_line = 109;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cdiv class=\"list-unstyled\"\u003E";
;pug_debug_line = 110;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli class=\"col-md-2 col-xs-2\"\u003E";
;pug_debug_line = 111;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cimg class=\"img-responsive center-block hvr-grow\" src=\"image\u002Flogo.jpeg\" alt=\"Dep1\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 112;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli class=\"col-md-2 col-xs-2\"\u003E";
;pug_debug_line = 113;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cimg class=\"img-responsive center-block hvr-grow\" src=\"image\u002Flogo.jpeg\" alt=\"Dep2\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 114;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli class=\"col-md-2 col-xs-2\"\u003E";
;pug_debug_line = 115;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cimg class=\"img-responsive center-block hvr-grow\" src=\"image\u002Flogo.jpeg\" alt=\"Dep3\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 116;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli class=\"col-md-2 col-xs-2\"\u003E";
;pug_debug_line = 117;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cimg class=\"img-responsive center-block hvr-grow\" src=\"image\u002Flogo.jpeg\" alt=\"Dep4\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 118;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli class=\"col-md-2 col-xs-2\"\u003E";
;pug_debug_line = 119;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cimg class=\"img-responsive center-block hvr-grow\" src=\"image\u002Flogo.jpeg\" alt=\"Dep5\"\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 120;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n        \u003Cli class=\"col-md-2 col-xs-2\"\u003E";
;pug_debug_line = 121;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cimg class=\"img-responsive center-block hvr-grow\" src=\"image\u002Flogo.jpeg\" alt=\"Dep6\"\u003E\u003C\u002Fli\u003E\n      \u003C\u002Fdiv\u003E\n    \u003C\u002Fdiv\u003E\n  \u003C\u002Fdiv\u003E\n\u003C\u002Fsection\u003E";
;pug_debug_line = 122;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Csection class=\"footer text-center\"\u003E";
;pug_debug_line = 123;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cdiv class=\"container\"\u003E";
;pug_debug_line = 124;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"row\"\u003E";
;pug_debug_line = 125;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cdiv class=\"col-lg-4\"\u003E";
;pug_debug_line = 126;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ci class=\"fas fa-video\"\u003E\u003C\u002Fi\u003E";
;pug_debug_line = 127;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca\u003E";
;pug_debug_line = 127;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Video\u003C\u002Fa\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 128;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cdiv class=\"col-lg-4\"\u003E";
;pug_debug_line = 129;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ci class=\"far fa-newspaper\"\u003E\u003C\u002Fi\u003E";
;pug_debug_line = 130;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca\u003E";
;pug_debug_line = 130;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Artical\u003C\u002Fa\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 131;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n      \u003Cdiv class=\"col-lg-4\"\u003E";
;pug_debug_line = 132;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ci class=\"fas fa-building\"\u003E\u003C\u002Fi\u003E";
;pug_debug_line = 133;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca\u003E";
;pug_debug_line = 133;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "Department\u003C\u002Fa\u003E\u003C\u002Fdiv\u003E\n    \u003C\u002Fdiv\u003E\n  \u003C\u002Fdiv\u003E";
;pug_debug_line = 134;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cdiv class=\"copyrigth\"\u003E";
;pug_debug_line = 135;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "CopyRigth &copy; 2021 ";
;pug_debug_line = 136;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 136;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + " Design By A7med Ragab\u003C\u002Fspan\u003E\u003C\u002Fdiv\u003E\n\u003C\u002Fsection\u003E";
;pug_debug_line = 137;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Csection class=\"loading\"\u003E";
;pug_debug_line = 138;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n  \u003Cdiv class=\"sk-chase\"\u003E";
;pug_debug_line = 139;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"sk-chase-dot\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 140;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"sk-chase-dot\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 141;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"sk-chase-dot\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 142;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"sk-chase-dot\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 143;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"sk-chase-dot\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 144;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n    \u003Cdiv class=\"sk-chase-dot\"\u003E\u003C\u002Fdiv\u003E\n  \u003C\u002Fdiv\u003E\n\u003C\u002Fsection\u003E";
;pug_debug_line = 145;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ca class=\"backtotop\" href=\"#\" style=\"display: inline;\"\u003E";
;pug_debug_line = 146;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\u003Ci class=\"fa fa-arrow-circle-up\"\u003E\u003C\u002Fi\u003E\u003C\u002Fa\u003E";
;pug_debug_line = 147;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Cscript src=\"js\u002Fjquery-1.11.1.min.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 148;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Cscript src=\"js\u002Fjquery.nicescroll.min.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 149;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Cscript src=\"js\u002Fbootstrap.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 150;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Cscript src=\"js\u002Fplugin.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 151;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Cscript src=\"js\u002Fwow.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 152;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "\n\u003Cscript\u003E";
;pug_debug_line = 153;pug_debug_filename = "C:\\Users\\a7med\\OneDrive\\Documents\\GitHub\\Project-1-Pug\u002Ffaq.pug";
pug_html = pug_html + "new WOW().init();\u003C\u002Fscript\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}